# Generated by Django 5.1.1 on 2024-09-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontent',
            name='contact_header_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='about_us2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='about_us3',
            field=models.TextField(blank=True, default=''),
        ),
    ]
